on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update_animes:
    runs-on: ubuntu-latest
    name: Updates README Anime List
    steps:
      - uses: actions/checkout@v2
      - uses: glup3/anilist-animes-action@v1.1.0
        with:
          ANILIST_USERNAME: 'SpreadSheeets'
          HEADER_TITLE: "My Anime Manga List"
          MANGA_GRID: "true"
          ANIME_GRID: "true"
          MARKDOWN_PATH: "./README.md"
